server:
  port: 9998
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instanceId: localhost:9998
    status-page-url: http://localhost:9998/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

spring:
  application:
    name: leishi-kernel-client
  datasource:
    url: jdbc:mysql://localhost:3306/leishi
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    open: true

  pool:
    enabled: true
    max-connections: 10   #连接池最大连接数
    idle-timeout: 30000   #空闲的连接过期时间，默认为30秒

mybatis:
  typeAliasesPackage: com.wxj.entity
  mapperLocations: classpath:mapper/*.xml
logging:
  file: \leishi\kernel.log
  level: 
    com.wxj.controller: debug
    com.wxj.dao: debug
    com.netflix.discovery: 'OFF'