server:
  port: 9992
spring:
  application:
    name: leishi-web-client
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates
    content-type: text/html 
    cache: false
    mode: LEGACYHTML5
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
      
zuul:
  host:
    max-per-route-connections: 20
    connections: 200
  routes:
    producer:
      path: /kernel/**
      serviceId: LEISHI-KERNEL-CLIENT
      retryable: true